site_name: utile
nav:
  - Home: index.md
  - Documentation: documentation.md
  - Examples: examples.md
  - GuideLines: guidelines.md
theme:
    name: mkdocs
    highlightjs: true
    hljs_style: dracula