

name: CI-utile


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: codecov/codecov-action@v1
    # Introduction
    - name: utile building
      run: echo utile

    # Runs test
    - name: Running tests
      run: |
        pip install coverage
        pip install codecov
        echo Building...
        cd tests
        coverage run test_processor.py
        coverage run test_threader.py
        coverage run test_timer.py
        codecov
